/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stdio.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_0 (GUI_ID_USER + 0x04)

// USER START (Optionally insert additional defines)
extern WM_HWIN CreateMenu(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern  U8 lcd_blk;                   //LCD±³¹âÁÁ¶È
extern WM_HWIN current_page;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Lcd_blk", ID_FRAMEWIN_0, 60, 20, 200, 220, WM_CF_MEMDEV, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 40, 64, 102, 53, WM_CF_MEMDEV_ON_REDRAW, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 51, 37, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 45, 150, 80, 25, WM_CF_MEMDEV_ON_REDRAW, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hItem;
  char str[4];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
      // USER START (Optionally insert code for reacting on notification message)
      WM_SetFocus(pMsg->hWin);
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
      TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
      sprintf(str, "%d", lcd_blk);
      TEXT_SetText(hItem, str);
      hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
      SLIDER_SetRange(hItem, 0, 100);
      SLIDER_SetNumTicks(hItem, 10);
      SLIDER_SetValue(hItem, lcd_blk);
      break;
      // USER END
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0:
        switch (NCode){
        case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
        case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            GUI_EndDialog(pMsg->hWin, 0);
            current_page = CreateMenu();
            WM_SetFocus(pMsg->hWin);
            // USER END
            break;
            // USER START (Optionally insert additional code for further notification handling)
            // USER END
        }

    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
          break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_SetFocus(pMsg->hWin);
        // USER END
          break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        SLIDER_SetRange(hItem, 0, 100);
        SLIDER_SetNumTicks(hItem, 10);
        GUI_X_Lock();
        lcd_blk = SLIDER_GetValue(hItem);
        GUI_X_Unlock();
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
        GUI_X_Lock();
        sprintf(str, "%d", lcd_blk);
        GUI_X_Unlock();
        TEXT_SetText(hItem, str);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLcd_blk
*/
WM_HWIN CreateLcd_blk(void);
WM_HWIN CreateLcd_blk(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
