/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x04)
#define ID_SPINBOX_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_0 (GUI_ID_USER + 0x07)
#define ID_TEXT_1 (GUI_ID_USER + 0x08)
#define ID_SPINBOX_1 (GUI_ID_USER + 0x09)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
extern WM_HWIN CreateMenu(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Sensor_config", ID_FRAMEWIN_0, 60, 19, 200, 220, WM_CF_MEMDEV, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Air_value", ID_SPINBOX_0, 92, 34, 80, 30, WM_CF_MEMDEV_ON_REDRAW, 0x0, 0 },
  { TEXT_CreateIndirect, "AIR_SOS (%)", ID_TEXT_0, 25, 42, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CO1_SOS (%)", ID_TEXT_1, 25, 104, 50, 30, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "CO1_value", ID_SPINBOX_1, 92, 97, 80, 30, WM_CF_MEMDEV_ON_REDRAW, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 53, 149, 80, 30, WM_CF_MEMDEV_ON_REDRAW, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern U8 air_set;                   //空气质量传感器阈值
extern U8 co1_set;                  //CO1传感器阈值
extern WM_HWIN current_page;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hItem;
  // USER END
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
      WM_SetFocus(pMsg->hWin);
      hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
      SPINBOX_SetRange(hItem, 10, 99);
      SPINBOX_SetStep(hItem, 1);
      GUI_X_Lock();
      SPINBOX_SetValue(hItem, air_set);
      GUI_X_Unlock();
      hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
      SPINBOX_SetRange(hItem, 10, 99);
      SPINBOX_SetStep(hItem, 1);
      GUI_X_Lock();
      SPINBOX_SetValue(hItem, co1_set);
      GUI_X_Unlock();
      break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'Air_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
          GUI_X_Lock();
          air_set = SPINBOX_GetValue(hItem);
          GUI_X_Unlock();
          WM_SetFocus(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_TEXT_0: // Notifications sent by 'Air'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END

      }
      break;
    case ID_TEXT_1: // Notifications sent by 'CO1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)


        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'CO1_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
          WM_SetFocus(pMsg->hWin);
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
          GUI_X_Lock();
          co1_set = SPINBOX_GetValue(hItem);
          GUI_X_Unlock();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
          GUI_EndDialog(pMsg->hWin, 0);
          GUI_X_Lock();
          current_page = CreateMenu();
          GUI_X_Unlock();
          WM_SetFocus(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSensor_config
*/
WM_HWIN CreateSensor_config(void);
WM_HWIN CreateSensor_config(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
